add api for classable def
aya-prover/aya-dev pull request #406
Opened 2022-05-04 10:19 UTC by tsao-chi

This is a part of https://github.com/aya-prover/aya-dev/issues/386

Currently aya only has callable def, which is definition with some linear anonymous arguments. However #386 will introduce a new type of def, which is called classable def. (`class = struct`)

This PR contains minimal changes and does introduce inconsistency in naming. For example, `def` might refer to callable def or all def. This inconsistency will be handled by future refactors.

2022-05-04 15:15 UTC, ice1000 requested changes
Can you merge `GenericDefVar`, `ClassDefVar` into `DefVar`?

Rest lgtm

2022-05-04 15:15 UTC, ice1000 commented on base/src/main/java/org/aya/core/def/GenericDef.java
> +public sealed interface GenericDef permits ClassDef, Def {
Maybe more methods? Like `accessibility`?

2022-05-04 22:23 UTC, ice1000 commented
@tsao-chi please address comments (I believe it's easy), I wish to merge this fast and furiously

2022-05-05 05:15 UTC, imkiva commented on base/src/main/java/org/aya/concrete/stmt/Stmt.java
> +        permits Remark, ClassDecl, Command, Decl, Generalize {
This indent is not needed because other `permits` does not have leading spaces.

2022-05-05 05:15 UTC, imkiva commented on base/src/main/java/org/aya/distill/CoreDistiller.java
> +        Doc.cat(term(Outer.ProjHead, term.of()), Doc.symbol("."), Doc.plain(String.valueOf(term.ix())));
Don't reformat existing code unless it is really unformatted.

2022-05-05 05:15 UTC, imkiva commented on base/src/main/java/org/aya/distill/CoreDistiller.java
> +      case Pat.End end -> Doc.bracedUnless(Doc.styled(KEYWORD, !end.isRight() ? "0" : "1"), end.explicit());
This code is unformatted, so this change is OK.

2022-05-05 06:19 UTC, tsao-chi commented
> Can you merge `GenericDefVar`, `ClassDefVar` into `DefVar`?
> 
> Rest lgtm

It appears to be not that easy I previously thought

2022-05-05 06:24 UTC, tsao-chi commented on base/src/main/java/org/aya/core/def/GenericDef.java
> +public sealed interface GenericDef permits ClassDef, Def {
Def doesn't have `accessibility`

2022-05-05 06:36 UTC, ice1000 commented
> > Can you merge `GenericDefVar`, `ClassDefVar` into `DefVar`?
> > 
> > Rest lgtm
> 
> It appears to be not that easy I previously thought

Can you elaborate? I am curious. What usage of DefVar/GenericVar makes it uneasy to use?

2022-05-05 06:40 UTC, tsao-chi commented
> > > Can you merge `GenericDefVar`, `ClassDefVar` into `DefVar`?
> > > Rest lgtm
> > 
> > 
> > It appears to be not that easy I previously thought
> 
> Can you elaborate? I am curious. What usage of DefVar/GenericVar makes it uneasy to use?

There were a number of places where `DefVar` is assumed to have a def with telescope such as `resolveStmt`

2022-05-05 07:00 UTC, ice1000 commented
@tsao-chi You can use if (defvar.concrete instanceof), I think it's okay

2022-05-07 02:55 UTC, ice1000 approved these changes
bors r+

2022-05-07 02:57 UTC, merged